window.ITEM_IMAGES = {
  "Swift Boots": "images/items/swift_boots.png",
  "Tough Boots": "images/items/tough_boots.png",
  "Magic Shoes": "images/items/magic_shoes.png",
  "Warrior Boots": "images/items/warrior_boots.png",
  "Arcane Boots": "images/items/arcane_boots.png",
  "Berserker's Fury": "images/items/berserkers_fury.png",
  "Scarlet Phantom": "images/items/scarlet_phantom.png",
  "Blade of Despair": "images/items/blade_of_despair.png",
  "Malefic Roar": "images/items/malefic_roar.png",
  "Wind of Nature": "images/items/wind_of_nature.png",
  "Windtalker": "images/items/windtalker.png",
  "Corrosion Scythe": "images/items/corrosion_scythe.png",
  "Demon Hunter Sword": "images/items/demon_hunter_sword.png",
  "Golden Staff": "images/items/golden_staff.png",
  "Hunter Strike": "images/items/hunter_strike.png",
  "Sea Halberd": "images/items/sea_halberd.png",
  "Clock of Destiny": "images/items/clock_of_destiny.png",
  "Lightning Truncheon": "images/items/lightning_truncheon.png",
  "Divine Glaive": "images/items/divine_glaive.png",
  "Holy Crystal": "images/items/holy_crystal.png",
  "Blood Wings": "images/items/blood_wings.png",
  "Calamity Reaper": "images/items/calamity_reaper.png",
  "Genius Wand": "images/items/genius_wand.png",
  "Enchanted Talisman": "images/items/enchanted_talisman.png",
  "Oracle": "images/items/oracle.png",
  "Necklace of Durance": "images/items/necklace_of_durance.png",
  "Concentrated Energy": "images/items/concentrated_energy.png",
  "Endless Battle": "images/items/endless_battle.png",
  "Bloodlust Axe": "images/items/bloodlust_axe.png",
  "Fleeting Time": "images/items/fleeting_time.png",
  "Dominance Ice": "images/items/dominance_ice.png",
  "Antique Cuirass": "images/items/antique_cuirass.png",
  "Athena's Shield": "images/items/athenas_shield.png",
  "Immortality": "images/items/immortality.png",
  "Blade Armor": "images/items/blade_armor.png",
  "Cursed Helmet": "images/items/cursed_helmet.png"
};
